[tool.poetry]
name = "leetcode"
version = "0.1.0"
description = ""
authors = ["yoshikikasama"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^7.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
